added webhook for NutanixClusterTemplate
This is required for alpha topology plan to not give error
Error: failed defaulting and validation on input objects: failed to run defaulting and validation on ClusterClasses: failed validation of cluster.x-k8s.io/v1beta1, Kind=ClusterClass workloads/my-test-cluster-template: ClusterClass.cluster.x-k8s.io "my-test-cluster-template" is invalid: []: Internal error: Clusters using ClusterClass my-test-cluster-template can not be retrieved: List on GroupVersionKind cluster.x-k8s.io/v1beta1, Kind=Cluster specifies selector on field spec.topology.class, but no index with name spec.topology.class has been registered for GroupVersionKind cluster.x-k8s.io/v1beta1, Kind=Cluster